image: mcr.microsoft.com/dotnet/sdk:7.0

variables:
  # 1) Name of directory where restore and build objects are stored.
  OBJECTS_DIRECTORY: "obj"
  # 2) Name of directory used for keeping restored dependencies.
  NUGET_PACKAGES_DIRECTORY: ".nuget"
  # 3) A relative path to the source code from project repository root.
  # NOTE: Please edit this path so it matches the structure of your project!
  SOURCE_CODE_PATH: "*/*/"

build:
  stage: build
  script:
    - "dotnet build --no-restore"

test:
  stage: test
  script:
    - "dotnet test --no-restore"

deploy:
  stage: deploy
  script: echo "test script"
  environment: production
