image: mcr.microsoft.com/dotnet/sdk:7.0

variables:
  OBJECTS_DIRECTORY: "obj"
  NUGET_PACKAGES_DIRECTORY: ".nuget"
  SOURCE_CODE_PATH: "*/*/"

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - "$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json"
    - "$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*"
    - "$NUGET_PACKAGES_DIRECTORY"

build:
  stage: build
  script:
    - "dotnet build"

test:
  stage: test
  script:
    - "dotnet test --no-restore"

deploy:
  stage: deploy
  script: echo "test script"
  environment: production
