pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"
  imageName: "harvest-docker"

steps:
  - script: dotnet restore
    displayName: "dotnet restore"

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: "dotnet build $(buildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: "dotnet test $(buildConfiguration)"
    inputs:
      command: test
      projects: "**/*Tests/*.csproj"
      arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: $(imageName)
      command: build
      Dockerfile: Dockerfile
      tags: latest
      arguments: "-o $(build.artifactstagingdirectory)"

  - task: bash@3
      displayname: save docker image
      inputs:
        targettype: 'inline'
        script: |
          docker save $(imageName):$(tag) -o $(pipeline.workspace)/harvest-image.tar

    - task: publishpipelineartifact@1
      inputs:
        targetpath: '$(pipeline.workspace)/harvest-image.tar'
        artifact: 'pipeline-artifact'
        publishlocation: 'pipeline'
